const AppAction = {
    LOADING_APP_START: 'LOADING_APP_START',
    CLOSE_LOADING_APP: 'CLOSE_LOADING_APP',
    LOADING_APP_POPUP_START: 'LOADING_APP_POPUP_START',
    CLOSE_LOADING_APP_POPUP: 'CLOSE_LOADING_APP_POPUP',

    FETCH_LOCALE_LIST: 'FETCH_LOCALE_LIST',
    FETCH_LOCALE_LIST_SUCCESS: 'FETCH_LOCALE_LIST_SUCCESS',

    SELECT_LOCALE: 'SELECT_LOCALE'

};

export default AppAction;
