const Sections = {
    top: {
        banner: 'bannerTop',
        contract_business: 'contract_business',
        system_business: 'system_business',
        client_slider: 'client_slider',
        products: 'products',
        list_jobs: 'list_jobs',
        tech_stack: 'tech_stack',
        suggestion_banner: 'suggestion_banner',
        video_url: 'video_url',
        aiBanner: 'ai_banner',
        onboarding: 'onboarding',
        onboardingVN: 'onboardingVN',
        onboardingEN: 'onboardingEN',
        implement: 'implement',
        implementVN: 'implementVN',
        implementEN: 'implementEN',
        aiSolution: 'ai_solution',
        aiSolutionVN: 'ai_solutionVN',
        aiSolutionEN: 'ai_solutionEN',
    },
    ai: {
        banner: 'banner',
        intro: 'intro',
        section_business_jp: 'section-business-JP',
        section_business_vn: 'section-business-VN',
        text_summary_jp: 'text-summary-JP',
        text_summary_vn: 'text-summary-VN',
        ai_different_text_jp: 'ai-different-text-JP',
        ai_different_text_vn: 'ai-different-text-VN',
        ai_sentence_matching_jp: 'ai-sentence-matching-JP',
        ai_sentence_matching_vn: 'ai-sentence-matching-VN',
    },
    companyInfo: {
        banner: 'banner',
        intro: 'intro',
        greetings: 'greetings',
        visions: 'visions',
        value: 'value',
        valueVN: 'valueVN',
        valueEN: 'valueEN',
        info_table: 'info_table',
        business_philosophy: 'business_philosophy',
        history: 'history',
        historyVN: 'historyVN',
        historyEN: 'historyEN',
    },
    business: {
        banner: 'banner',
        intro: 'intro',
        outsource: 'outsource',
        staffing: 'staffing',
    },
    lab: {
        banner: 'banner',
        overview: 'overview',
        model: 'model',
        overviewVN: 'overviewVN',
        overviewEN: 'overviewEN',
    },
    contract: {
        banner: 'banner',
        overview: 'overview',
        overviewVN: 'overviewVN',
        overviewEN: 'overviewEN',
        model: 'model',
    },
    contact: {
        banner: 'banner',
    },
    recruitment: {
        banner: 'banner',
    },
    product: {},
    holon: {
        banner: 'banner',
        introduce: 'introduce',
        overview: 'overview',
        concept: 'concept',
        conceptVN: 'conceptVN',
        conceptEN: 'conceptEN',
    },
};
export default Sections;
