const AuthAction = {
    // login
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    // forgot-pw
    GET_OTP_REQUEST: 'GET_OTP_REQUEST',
    GET_OTP_SUCCESS: 'GET_OTP_SUCCESS',
    RESET_PW_REQUEST: 'RESET_PW_REQUEST',
    RESET_PW_SUCCESS: 'RESET_PW_SUCCESS',
    //
    GET_DETAIL_USER_START: 'GET_DETAIL_USER_START',
    GET_DETAIL_USER_SUCCESS: 'GET_DETAIL_USER_SUCCESS',
    GET_DETAIL_USER_ERROR: 'GET_DETAIL_USER_ERROR',
};

export default AuthAction;
