stages:
  - deploy

deploy:
  stage: deploy
  only:
    - web
    - master
    - dev
  before_script:
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - mkdir -p ~/.ssh
    - ssh-keyscan -H -p $SSH_PORT $SSH_SERVER_DOMAIN >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ls -a
    - pwd
    - whoami
    - php -v
    - composer -v
    - mkdir -p build
  script:
    - composer install
    - composer dump-autoload
    - zip -r ./build/source.zip *
    - echo 'put -r ./build/source.zip' | sftp -oPort=$SSH_PORT $SSH_USER@$SSH_SERVER_DOMAIN:$SERVER_DIR &&
    - >
      ssh $SSH_USER@$SSH_SERVER_DOMAIN -p $SSH_PORT
      "cd $SERVER_DIR;
      unzip -o source.zip;
      rm source.zip;
      chown -R $USER_DEPLOY:$USER_DEPLOY $SERVER_DIR"
    - >
      ssh $SSH_USER@$SSH_SERVER_DOMAIN -p $SSH_PORT
      "cd $SERVER_DIR;
      php artisan cache:clear;
      php artisan route:clear;
      php artisan config:clear;
      php artisan view:clear;
      php artisan storage:link"
  environment: $CI_COMMIT_REF_NAME
