version: "3"

services:
    postgres_db:
        image: postgres:15
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_PASSWORD=toploop
            - POSTGRES_USER=toploop
            - POSTGRES_DB=toploop
        restart: unless-stopped
        ports:
            - "5434:5432"
        volumes:
            - postgres_db:/var/lib/postgresql/data

volumes:
    postgres_db:
        driver: local