const AccountAction = {
    FETCH_ACCOUNTS_LIST_START: "FETCH_ACCOUNTS_LIST_START",
    FETCH_ACCOUNTS_LIST_SUCCESS: "FETCH_ACCOUNTS_LIST_SUCCESS",

    DELETE_ACCOUNT_START: "DELETE_ACCOUNT_START",
    DELETE_ACCOUNT_SUCCESS: "DELETE_ACCOUNT_SUCCESS",

    GET_ACCOUNT_START: "GET_ACCOUNT_START",
    GET_ACCOUNT_SUCCESS: "GET_ACCOUNT_SUCCESS",

    EDIT_ACCOUNT_START: "EDIT_ACCOUNT_START",
    EDIT_ACCOUNT_SUCCESS: "EDIT_ACCOUNT_SUCCESS",

    DELETE_MANY_ACCOUNT_START: "DELETE_MANY_ACCOUNT_START",
    DELETE_MANY_ACCOUNT_SUCCESS: "DELETE_MANY_ACCOUNT_SUCCESS",

    CREATE_ACCOUT_START: "CREATE_ACCOUT_START",
    CREATE_ACCOUT_SUCCESS: "CREATE_ACCOUT_SUCCESS",

    CHANGE_PASSWORD_BY_USER_START: "CHANGE_PASSWORD_BY_USER_START",
    CHANGE_PASSWORD_BY_USER_SUCCESS: "CHANGE_PASSWORD_BY_USER_SUCCESS",

};

export default AccountAction;
